### ISSUE TITLE
I have some problem with the raw data you provided in the link of your paper. Those data seemed to be non-filtered matrix. Could you please help to provide filtered_feature_bc_matrix data? many thanks to this

### ISSUE THREAD

**Issue by zclecle2** [vsoch/repo2docker-r#1]

**Comment by vsoch** [comment]
> "the link of your paper"

what paper?

**Comment by zclecle2** [comment]
The original paper, "Single-cell transcriptomic analysis of the adult mouse spinal cord reveals molecular diversity of autonomic and skeletal motor neurons". And the link is here: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE161621. Thanks

**Comment by vsoch** [comment]
I don’t know how that’s related to this repo, sorry!
